---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/aws-cli"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(dev-deps)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore(ci-deps)
