---
name: DNF Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  dnf-check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Check the versions
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          packages=$(grep -E '^[[:space:]]+[a-zA-Z0-9._+-]+-[^-]+-[^-]+[[:space:]]*\\?[[:space:]]*$' "${GITHUB_REPOSITORY#*/docker-}/Dockerfile" | sed -E 's/^[[:space:]]+//; s/[[:space:]]*\\?[[:space:]]*$//; s/-[^-]+-[^-]+$//' | tr '\n' ' ')
          echo "Checking packages: ${packages}"
          docker run --pull always -t --user root -e PACKAGES="${packages}" --entrypoint /bin/sh "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" -c 'if ! dnf upgrade -y --refresh $PACKAGES | tee -a /dev/stderr | grep -q -e "^Nothing to do."; then exit 1; fi'
