---
name: DNF Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        run: docker run --pull always -t --user root --entrypoint /bin/sh "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" -c 'dnf upgrade -y | tee -a /dev/stderr | grep -q -v -e "^Nothing to do." && exit 1'
