name: Keep alive
on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Generate
      run: |
        git config user.email "check-action@github"
        git config user.name "check-action"
        git commit --allow-empty -m "Trigger build"
        git push origin "${GITHUB_REF#refs/heads/}"
