---
name: PIP Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        # FIXME @TL workaround until Amazon Linux gets a pipx package
        run: docker run --pull always -t --user root --entrypoint /bin/sh "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" -c 'pip3 list --outdated | tee -a /dev/stderr | grep -q -e "^pipx " && exit 1'
