---
name: PIP Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        # FIXME @TL workaround until Amazon Linux gets a pipx package
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          docker run --pull always -t --user root --entrypoint /bin/sh "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" -c 'if pip list --outdated | tee -a /dev/stderr | grep -q -e "^pipx "; then exit 1; fi'
