name: PIP Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        run: |
          docker run --pull always -t --user root --entrypoint /bin/sh "leplusorg/${GITHUB_REPOSITORY#*/docker-}:main" /bin/sh -c '
            # FIXME @TL workaround until Amazon Linux gets a pipx package
            if pip3 list --outdated | tee -a /dev/stderr | grep -q -e '"'"'^pipx '"'"' ; then
              exit 1
            fi
          '
